### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by m1024** [vforteli/Flexinets.Radius.RadiusClient#6]
Please update nuget package, because it's not contains [commit](https://github.com/vforteli/Flexinets.Radius.RadiusClient/commit/981f0b0f8826a6577ab64594562533cb6f11f8cc).
It's important because without it, the object is not collected by the garbage collector because of the infinite loop, which leads to leaks and high CPU load.

**Comment by vforteli** [comment]
Good point. I dont think ive ever used this for anything long running so has gone without noticing for quite some time. That whole section should be cleaned up and probably use cancellation tokens insteadSent from my iPhoneOn 24. Jan 2023, at 21.15, Макар ***@***.***> wrote:﻿
Please update nuget package, because it's not contained commit.
It's important because without it, the object is not destroyed by the garbage collector because of the infinite loop, which leads to leaks and high CPU load.
